### ISSUE TITLE
Hoàn thiện CRUD backend

### ISSUE THREAD

**Issue by cubo142** [cubo142/QuanLyCongVan#1]
- Hoàn thiện các routes, controller, model trong BE:
- Tạo các routes, controllers chức năng cơ bản sau:
+ READ: đọc 1 bản ghi, đọc toàn bộ bản ghi
+ CREATE: tạo 1 dữ liệu
+ UPDATE: cập nhật 1 dữ liệu
+ DELETE: Xóa 1 dữ liệu

Các model cần bổ sung: bophan, linhvuc,chudecvan, nhanvien

**Comment by cubo142** [comment]
Có vấn đề thì note thẳng vô đây

**Comment by luongdthong2889** [comment]
xong hết rồi , m check branch của t đi
